In [3]:
import pandas as pd
#import numpy as np

In [4]:
nse=pd.read_csv('./data/NSE.csv')

In [5]:
nse.head()

         Date      Price       Open       High        Low     Vol. Change %
0  22/12/2023  74,023.27  74,288.88  74,430.47  73,993.49  423.20M   -0.36%
1  21/12/2023  74,289.02  73,397.71  74,292.76  73,397.71  760.93M    1.21%
2  20/12/2023  73,397.71  72,470.10  73,399.61  72,470.10  552.22M    1.28%
3  19/12/2023  72,470.10  72,404.91  72,489.21  72,320.32  411.06M    0.09%
4  18/12/2023  72,404.91  72,389.23  72,413.13  72,276.75  324.15M    0.02%

In [6]:
nse.describe()

              Date      Price       Open       High        Low   Vol. Change %
count         2948       2948       2948       2948       2948   1651     2948
unique        2948       2939       2938       2932       2938   1614      501
top     22/12/2023  29,964.79  20,658.28  37,259.65  37,278.34  1.17B    0.02%
freq             1          2          3          4          3      3       35

In [8]:
print(nse.shape)

(2948, 7)

In [10]:
print(nse.dtypes)

Date        object
Price       object
Open        object
High        object
Low         object
Vol.        object
Change %    object
dtype: object

In [11]:
print(nse.isnull().sum())

Date           0
Price          0
Open           0
High           0
Low            0
Vol.        1297
Change %       0
dtype: int64

# What is the date range — oldest to newest?

In [14]:
nse['Date'] = pd.to_datetime(nse['Date'])
print(nse['Date'].min())
print(nse['Date'].max())

2012-01-30 00:00:00
2023-12-22 00:00:00

# How many records are we dealing with?

In [16]:
nse.size

20636

# What columns do we have?

In [17]:
nse.columns

Index(['Date', 'Price', 'Open', 'High', 'Low', 'Vol.', 'Change %'], dtype='object')

# Where is the data dirty or missing?

In [18]:
nse.isnull().sum()

Date           0
Price          0
Open           0
High           0
Low            0
Vol.        1297
Change %       0
dtype: int64

# Which company has the highest average closing price?

In [19]:
nse['Price'] = nse['Price'].str.replace(',', '').astype(float)

In [20]:
nse

           Date     Price       Open       High        Low     Vol. Change %
0    2023-12-22  74023.27  74,288.88  74,430.47  73,993.49  423.20M   -0.36%
1    2023-12-21  74289.02  73,397.71  74,292.76  73,397.71  760.93M    1.21%
2    2023-12-20  73397.71  72,470.10  73,399.61  72,470.10  552.22M    1.28%
3    2023-12-19  72470.10  72,404.91  72,489.21  72,320.32  411.06M    0.09%
4    2023-12-18  72404.91  72,389.23  72,413.13  72,276.75  324.15M    0.02%
...         ...       ...        ...        ...        ...      ...      ...
2943 2012-02-03  20877.64  20,822.00  20,863.93  20,786.35      NaN    0.27%
2944 2012-02-02  20822.00  20,872.94  20,900.58  20,785.40      NaN    0.15%
2945 2012-02-01  20790.88  20,875.34  20,941.03  20,790.88      NaN   -0.41%
2946 2012-01-31  20875.83  20,818.56  21,009.92  20,789.48      NaN    0.70%
2947 2012-01-30  20731.72  20,939.10  20,950.02  20,731.72      NaN   -0.77%

[2948 rows x 7 columns]